export { default as useInventoryCheck } from "./useInventoryCheck";
export {
  extractBuyGet,
  getMatrixInfo,
  formatPrice,
  formatCurrency,
  calculateTotalPrice,
  calculateTotalCurrency,
  getTotalPriceAfterDiscount,
  fetchLocationByPostalCode,
  calculateActualQuantity,
  createQuantityHandlers,
  useQuantityHandlers,
  fetchRegionByCode,
  validatePhone,
  validateCanadianPostalCode,
  validateUSZipCode,
  validatePostalCode,
  handleTaxShippingEstimate,
} from "./config";
